using System.Collections.Frozen;

namespace BatchRenamePro.App.Localization;

/// <summary>A language the application ships.</summary>
/// <param name="Culture">BCP-47 tag, as stored in settings.</param>
/// <param name="NativeName">The language's name written in that language.</param>
public sealed record LanguageOption(string Culture, string NativeName)
{
    /// <summary>The language's name, which is also what a screen reader reads from the picker.</summary>
    /// <remarks>
    /// A combo box entry has no label of its own, so its automation peer falls back to this. Left as
    /// the compiler-generated record ToString it would announce the whole "LanguageOption { … }" shape.
    /// </remarks>
    public override string ToString() => NativeName;
}

/// <summary>
/// Every user-visible string, one table per shipped language.
/// </summary>
/// <remarks>
/// Kept as plain dictionaries rather than satellite resource assemblies for one reason: the language
/// can then be swapped while the window is open, which is what people expect from a language picker
/// in the settings page. The keys that start with <c>rule.</c>, <c>item.</c>, <c>name.</c>,
/// <c>token.</c> and <c>preset.</c> are the stable codes the culture-free core layer emits — the core
/// never formats a sentence for a human, it reports a code and this table turns it into words.
/// </remarks>
internal static class StringCatalog
{
    /// <summary>The language used when a culture has no table and when a key is missing from one.</summary>
    public const string FallbackCulture = "en-US";

    /// <summary>The languages offered in the settings page, in display order.</summary>
    public static IReadOnlyList<LanguageOption> Languages { get; } =
    [
        new("zh-CN", "简体中文"),
        new("en-US", "English")
    ];

    private static readonly FrozenDictionary<string, FrozenDictionary<string, string>> Tables =
        new Dictionary<string, FrozenDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["zh-CN"] = Chinese.ToFrozenDictionary(StringComparer.Ordinal),
            ["en-US"] = English.ToFrozenDictionary(StringComparer.Ordinal)
        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    /// <summary>Whether a language has a table of its own.</summary>
    /// <param name="culture">A BCP-47 tag.</param>
    public static bool IsSupported(string culture) => Tables.ContainsKey(culture);

    /// <summary>Looks up a key, falling back to English and then to the key itself.</summary>
    /// <param name="culture">A BCP-47 tag.</param>
    /// <param name="key">The string's identifier.</param>
    /// <remarks>
    /// Returning the key is deliberate: a missing translation shows up as <c>rule.replace.name</c> in
    /// the UI, which is obvious in a screenshot, instead of a blank label nobody notices.
    /// </remarks>
    public static string Get(string culture, string key)
    {
        if (Tables.TryGetValue(culture, out var table) && table.TryGetValue(key, out var value)) return value;
        if (Tables[FallbackCulture].TryGetValue(key, out var fallback)) return fallback;
        return key;
    }

    private static Dictionary<string, string> Chinese => new(StringComparer.Ordinal)
    {
        // ---- shell ----
        ["app.name"] = "批量文件改名 Pro",
        ["app.tagline"] = "预览确认后再动手的批量重命名工具",
        ["nav.rename"] = "重命名",
        ["nav.presets"] = "预设",
        ["nav.history"] = "历史记录",
        ["nav.settings"] = "设置",
        ["nav.about"] = "关于",
        ["nav.toggle"] = "展开或收起导航",
        ["window.minimize"] = "最小化",
        ["window.maximize"] = "最大化",
        ["window.restore"] = "向下还原",
        ["window.close"] = "关闭",

        // ---- source list ----
        ["source.title"] = "文件",
        ["source.addFolder"] = "添加文件夹",
        ["source.addFiles"] = "添加文件",
        ["source.clear"] = "清空",
        ["source.remove"] = "移出列表",
        ["source.refresh"] = "重新扫描",
        ["source.recursive"] = "包含子文件夹",
        ["source.target"] = "对象",
        ["source.filter"] = "筛选",
        ["source.filter.hint"] = "*.jpg;*.png（留空表示全部）",
        ["source.exclude.hint"] = "排除，如 *.tmp",
        ["source.empty.title"] = "还没有选择文件",
        ["source.empty.hint"] = "把文件或文件夹拖到这里，或点击「添加文件夹」。",
        ["source.count"] = "已选 {0} 项",
        ["source.dropHint"] = "松开即可添加",
        ["source.noneAdded"] = "这些位置里没有找到符合条件的文件",

        // ---- rules ----
        ["rules.title"] = "规则",
        ["rules.add"] = "添加规则",
        ["rules.empty.title"] = "还没有规则",
        ["rules.empty.hint"] = "规则自上而下依次作用于每个文件名。先加一条试试。",
        ["rules.enable"] = "启用这条规则",
        ["rules.moveUp"] = "上移",
        ["rules.moveDown"] = "下移",
        ["rules.duplicate"] = "复制一份",
        ["rules.remove"] = "删除规则",
        ["rules.clear"] = "清空规则",
        ["rules.scope"] = "作用范围",

        ["rule.pattern.name"] = "按模板重命名",
        ["rule.pattern.summary"] = "用变量拼出全新的名字",
        ["rule.replace.name"] = "查找替换",
        ["rule.replace.summary"] = "把一段文字换成另一段",
        ["rule.insert.name"] = "插入文本",
        ["rule.insert.summary"] = "在开头、结尾或指定位置加字",
        ["rule.remove.name"] = "删除字符",
        ["rule.remove.summary"] = "按位置、文本或字符类型删除",
        ["rule.case.name"] = "大小写",
        ["rule.case.summary"] = "统一转换大小写",
        ["rule.extension.name"] = "扩展名",
        ["rule.extension.summary"] = "修改或统一扩展名",
        ["rule.number.name"] = "编号",
        ["rule.number.summary"] = "加上连续序号",
        ["rule.cleanup.name"] = "整理清洗",
        ["rule.cleanup.summary"] = "去空格、去符号、限制长度",

        // rule editors
        ["rule.pattern.label"] = "命名模板",
        ["rule.pattern.hint"] = "例如 {name}_{index:000}",
        ["rule.pattern.insertToken"] = "插入变量",
        ["rule.replace.find"] = "查找",
        ["rule.replace.replaceWith"] = "替换为",
        ["rule.replace.useRegex"] = "使用正则表达式",
        ["rule.replace.ignoreCase"] = "忽略大小写",
        ["rule.replace.firstOnly"] = "只替换第一处",
        ["rule.replace.regexHint"] = "可用 $1 $2 引用捕获组",
        ["rule.insert.text"] = "要插入的文本",
        ["rule.insert.position"] = "位置",
        ["rule.insert.index"] = "第几个字符",
        ["rule.remove.mode"] = "方式",
        ["rule.remove.count"] = "字符数",
        ["rule.remove.position"] = "起始位置",
        ["rule.remove.text"] = "文本",
        ["rule.remove.keep"] = "保留这些符号",
        ["rule.case.mode"] = "转换为",
        ["rule.extension.mode"] = "操作",
        ["rule.extension.newExtension"] = "新扩展名",
        ["rule.number.position"] = "位置",
        ["rule.number.separator"] = "分隔符",
        ["rule.number.start"] = "起始值",
        ["rule.number.step"] = "步长",
        ["rule.number.padding"] = "位数",
        ["rule.number.style"] = "编号样式",
        ["rule.number.groupSize"] = "每组数量",
        ["rule.sequence.title"] = "编号设置",
        ["rule.cleanup.trimEnds"] = "去掉首尾空格",
        ["rule.cleanup.collapseWhitespace"] = "合并连续空格",
        ["rule.cleanup.replaceSpaces"] = "把空格替换为",
        ["rule.cleanup.removeDiacritics"] = "去掉字母上的音标符号",
        ["rule.cleanup.stripInvalid"] = "替换 Windows 不允许的字符",
        ["rule.cleanup.invalidReplacement"] = "替换为",
        ["rule.cleanup.maxLength.label"] = "最大长度（0 表示不限制）",

        // ---- rule diagnostics (codes emitted by the core) ----
        ["rule.pattern.empty"] = "命名模板不能为空。",
        ["rule.pattern.unknownToken"] = "模板里有无法识别的变量，它会原样出现在文件名中。",
        ["rule.replace.emptyFind"] = "请填写要查找的内容。",
        ["rule.replace.badRegex"] = "正则表达式还不完整或有语法错误。",
        ["rule.insert.emptyText"] = "请填写要插入的文本。",
        ["rule.insert.negativeIndex"] = "位置不能是负数。",
        ["rule.remove.emptyText"] = "请填写要删除的文本。",
        ["rule.remove.negativePosition"] = "起始位置不能是负数。",
        ["rule.extension.empty"] = "请填写新的扩展名。",
        ["rule.extension.invalidChars"] = "扩展名里有 Windows 不允许的字符。",
        ["rule.cleanup.maxLength"] = "最大长度太小了，会把名字截没。",
        ["rule.cleanup.badReplacement"] = "替换字符本身就是 Windows 不允许的字符。",
        ["rule.sequence.padding"] = "编号位数超出了允许范围。",
        ["rule.sequence.zeroStep"] = "步长为 0，所有文件会得到同一个编号。",
        ["rule.sequence.groupSize"] = "每组数量至少为 1。",
        ["rule.sequence.alphabeticStart"] = "字母编号要从 1 开始。",
        ["rule.sequence.romanStart"] = "罗马数字编号要从 1 开始。",

        // ---- preview ----
        ["preview.title"] = "预览",
        ["preview.column.original"] = "现在的名字",
        ["preview.column.proposed"] = "改名之后",
        ["preview.column.status"] = "状态",
        ["preview.empty.title"] = "预览会显示在这里",
        ["preview.empty.hint"] = "选好文件、加上规则，改名结果会实时出现。",
        ["preview.showOnlyChanged"] = "只看有变化的",
        ["preview.sameName"] = "（不变）",
        ["preview.conflictPolicy"] = "冲突处理",

        ["item.ready"] = "将被重命名",
        ["item.unchanged"] = "名字没有变化",
        ["item.skipped"] = "已跳过",
        ["item.missing"] = "文件已不存在",
        ["item.duplicateTarget"] = "和本批次里的另一项重名",
        ["item.existsOnDisk"] = "目标名字已被磁盘上的文件占用",
        ["item.autoResolved"] = "已自动加序号避开重名",
        ["item.ruleError"] = "规则有错误",
        ["item.ruleFailed"] = "这一项应用规则时出错",

        ["name.empty"] = "名字不能为空。",
        ["name.invalidChars"] = "名字里有 Windows 不允许的字符。",
        ["name.reserved"] = "这是 Windows 的保留设备名。",
        ["name.tooLong"] = "名字太长了。",
        ["name.trailingDotOrSpace"] = "名字不能以点或空格结尾。",
        ["name.leadingSpace"] = "名字不能以空格开头。",

        ["summary.ready"] = "{0} 项将重命名",
        ["summary.unchanged"] = "{0} 项不变",
        ["summary.problems"] = "{0} 项有问题",
        ["summary.autoResolved"] = "{0} 项自动加了序号",
        ["summary.nothing"] = "没有需要改名的文件",

        // ---- presets ----
        ["presets.title"] = "预设",
        ["presets.subtitle"] = "把常用的规则组合存下来，下次一键套用。",
        ["presets.apply"] = "套用",
        ["presets.applied"] = "已套用预设「{0}」",
        ["presets.save"] = "保存为预设",
        ["presets.saveCurrent"] = "保存当前规则",
        ["presets.saveTitle"] = "保存预设",
        ["presets.namePrompt"] = "给这套规则起个名字",
        ["presets.nameReserved"] = "这个名字被内置预设占用了，换一个吧。",
        ["presets.delete"] = "删除预设",
        ["presets.deleteConfirm"] = "确定要删除预设「{0}」吗？",
        ["presets.import"] = "导入…",
        ["presets.export"] = "导出…",
        ["presets.builtIn"] = "内置",
        ["presets.custom"] = "我的预设",
        ["presets.ruleCount"] = "{0} 条规则",
        ["presets.empty.title"] = "还没有预设",
        ["presets.empty.hint"] = "在「重命名」页配好规则后，点「保存当前规则」就能存成预设。",
        ["presets.saved"] = "已保存预设「{0}」",
        ["presets.imported"] = "已导入预设「{0}」",
        ["presets.exported"] = "已导出预设「{0}」",
        ["presets.overwrite"] = "已存在同名预设，要覆盖吗？",
        ["presets.filter"] = "预设文件 (*.json)|*.json",

        ["preset.photos"] = "照片按日期编号",
        ["preset.photos.description"] = "改成「2025-11-27_001」这样的名字",
        ["preset.numbering"] = "保留原名并加编号",
        ["preset.numbering.description"] = "在原来的名字后面接上 _001",
        ["preset.webSafe"] = "适合上传的名字",
        ["preset.webSafe.description"] = "全小写、用连字符代替空格、去掉特殊字符",
        ["preset.datePrefix"] = "加上修改日期前缀",
        ["preset.datePrefix.description"] = "在名字前面加上文件的修改日期",
        ["preset.tidy"] = "整理杂乱的名字",
        ["preset.tidy.description"] = "合并空格、去掉多余符号和首尾空白",
        ["preset.lowerExt"] = "扩展名转小写",
        ["preset.lowerExt.description"] = "只把 .JPG 这样的扩展名改成小写",

        // ---- tokens ----
        ["tokens.title"] = "可用变量",
        ["tokens.hint"] = "点击即可插入到模板中。",
        ["tokens.category.text"] = "文本",
        ["tokens.category.number"] = "数字",
        ["tokens.category.time"] = "时间",
        ["tokens.category.unique"] = "唯一值",

        ["token.name"] = "当前的主文件名",
        ["token.ext"] = "扩展名，含点",
        ["token.original"] = "最初的完整文件名",
        ["token.parent"] = "所在文件夹的名字",
        ["token.nameUpper"] = "主文件名转大写",
        ["token.nameLower"] = "主文件名转小写",
        ["token.nameTitle"] = "主文件名每个词首字母大写",
        ["token.index"] = "序号",
        ["token.indexPadded"] = "补零到三位的序号",
        ["token.total"] = "本批次的文件总数",
        ["token.size"] = "文件大小，字节",
        ["token.sizeMb"] = "文件大小，MB",
        ["token.date"] = "今天的日期",
        ["token.time"] = "当前时间",
        ["token.dateFormat"] = "自定义格式的日期",
        ["token.created"] = "文件的创建日期",
        ["token.modified"] = "文件的修改日期",
        ["token.year"] = "年",
        ["token.month"] = "月",
        ["token.day"] = "日",
        ["token.guid"] = "随机的唯一标识",
        ["token.rand"] = "六位随机字符",

        // ---- actions ----
        ["action.run"] = "开始重命名",
        ["action.runCount"] = "重命名 {0} 项",
        ["action.cancel"] = "取消",
        ["action.close"] = "关闭",
        ["action.ok"] = "确定",
        ["action.undo"] = "撤销",
        ["action.undoLast"] = "撤销上一次",
        ["action.retry"] = "重试",
        ["action.copy"] = "复制",
        ["action.openFolder"] = "打开所在文件夹",
        ["action.toggleTheme"] = "切换浅色/深色",
        ["action.dismiss"] = "知道了",

        ["run.confirmTitle"] = "确认重命名",
        ["run.confirmBody"] = "即将重命名 {0} 项文件。这个操作可以撤销。",
        ["run.working"] = "正在重命名…",
        ["run.progress"] = "{0} / {1}",
        ["run.done"] = "已重命名 {0} 项",
        ["run.undone"] = "已撤销 {0} 项",
        ["run.cancelled"] = "已取消，之前的改动已全部还原",
        ["run.failed"] = "重命名失败",
        ["run.rolledBack"] = "出错了，所有改动都已还原，文件保持原样。",
        ["run.unrecovered"] = "出错了，其中 {0} 项没能还原，请在历史记录里查看。",

        // ---- history ----
        ["history.title"] = "历史记录",
        ["history.subtitle"] = "每一次批量改名都记在这里，随时可以撤销。",
        ["history.empty.title"] = "还没有记录",
        ["history.empty.hint"] = "完成一次批量改名后，这里就会出现可以撤销的条目。",
        ["history.itemCount"] = "{0} 项",
        ["history.multipleFolders"] = "多个文件夹",
        ["history.undo"] = "撤销这一次",
        ["history.undoConfirm"] = "会把这一批 {0} 项文件的名字改回原来的样子。确定吗？",
        ["history.forget"] = "从历史中删除，不改动文件",
        ["history.clear"] = "清空历史",
        ["history.clearConfirm"] = "确定要清空全部历史记录吗？文件不会被改动。",
        ["history.undone"] = "已撤销",
        ["history.undoFailed"] = "撤销失败，可能文件已被移动或改名。",

        // ---- settings ----
        ["settings.title"] = "设置",
        ["settings.subtitle"] = "改动即时生效，不需要保存。",
        ["settings.section.appearance"] = "外观",
        ["settings.theme"] = "主题",
        ["settings.theme.hint"] = "选「跟随系统」时会随 Windows 的浅色/深色设置自动切换。",
        ["settings.backdrop"] = "窗口材质",
        ["settings.backdrop.hint"] = "需要 Windows 11 22H2 及以上；系统不支持时自动使用纯色。",
        ["settings.backdrop.unavailable"] = "当前系统版本不支持窗口材质，这里的选择会在系统更新后生效。",
        ["settings.language"] = "语言",
        ["settings.language.hint"] = "切换后立即生效，不用重启。",
        ["settings.navigationExpanded"] = "启动时展开侧边导航",
        ["settings.section.defaults"] = "默认行为",
        ["settings.confirmBeforeRun"] = "开始重命名前先确认",
        ["settings.confirmBeforeRun.hint"] = "关掉之后点「开始重命名」会直接执行，但仍然可以撤销。",
        ["settings.recursive"] = "默认包含子文件夹",
        ["settings.recursive.hint"] = "添加文件夹时，是否连同里面的所有层级一起扫描。",
        ["settings.scanTarget"] = "默认扫描对象",
        ["settings.conflictPolicy"] = "默认冲突处理",
        ["settings.conflictPolicy.hint"] = "两个文件想用同一个名字时的默认做法。",
        ["settings.historyLimit"] = "保留的历史记录条数",
        ["settings.historyLimit.hint"] = "5 到 500 之间，超出的旧记录会被自动清理。",
        ["settings.section.data"] = "数据",
        ["settings.dataFolder"] = "数据文件夹",
        ["settings.openDataFolder"] = "打开数据文件夹",
        ["settings.reset"] = "恢复默认设置",
        ["settings.reset.hint"] = "只重置设置，预设和历史记录不受影响。",
        ["settings.resetConfirm"] = "确定要把所有设置恢复成默认值吗？",
        ["settings.resetDone"] = "设置已恢复默认",

        // ---- about ----
        ["about.version"] = "版本",
        ["about.repository"] = "项目主页",
        ["about.issues"] = "反馈问题",
        ["about.license"] = "开源许可",
        ["about.license.mit"] = "MIT 许可证",
        ["about.environment"] = "运行环境",
        ["about.runtime"] = ".NET 运行时",
        ["about.os"] = "操作系统",
        ["about.tokens"] = "可用变量速查",
        ["about.tokens.hint"] = "这些变量可以写进「按模板重命名」的模板里，点一下即可复制。",
        ["about.copyright"] = "以 MIT 许可证开源，欢迎自由使用、修改和分发。",

        // ---- generic ----
        ["common.yes"] = "是",
        ["common.no"] = "否",
        ["common.on"] = "开",
        ["common.off"] = "关",
        ["common.search"] = "搜索",
        ["common.none"] = "无",
        ["common.error"] = "出错了",
        ["common.warning"] = "注意",
        ["common.loading"] = "正在加载…",
        ["error.unexpected"] = "出现了意外错误：{0}",
        ["error.unexpected.fallback"] = "程序遇到意外错误，需要关闭。详细信息已写入日志文件。",
        ["time.justNow"] = "刚刚",
        ["time.minutesAgo"] = "{0} 分钟前",
        ["time.hoursAgo"] = "{0} 小时前",
        ["time.daysAgo"] = "{0} 天前",

        // ---- enums ----
        ["enum.CaseMode.Lower"] = "全部小写",
        ["enum.CaseMode.Upper"] = "全部大写",
        ["enum.CaseMode.Title"] = "每个词首字母大写",
        ["enum.CaseMode.Sentence"] = "句首字母大写",
        ["enum.CaseMode.Invert"] = "反转大小写",
        ["enum.ExtensionMode.Keep"] = "保持不变",
        ["enum.ExtensionMode.Lower"] = "转为小写",
        ["enum.ExtensionMode.Upper"] = "转为大写",
        ["enum.ExtensionMode.Replace"] = "替换为",
        ["enum.ExtensionMode.Remove"] = "删除扩展名",
        ["enum.ExtensionMode.AddIfMissing"] = "没有时才添加",
        ["enum.InsertPosition.Prefix"] = "放在开头",
        ["enum.InsertPosition.Suffix"] = "放在结尾",
        ["enum.InsertPosition.AtIndex"] = "从左数第 N 个字符前",
        ["enum.InsertPosition.FromEnd"] = "从右数第 N 个字符前",
        ["enum.RemoveMode.FromStart"] = "开头的 N 个字符",
        ["enum.RemoveMode.FromEnd"] = "结尾的 N 个字符",
        ["enum.RemoveMode.Range"] = "指定位置的 N 个字符",
        ["enum.RemoveMode.Text"] = "指定的文本",
        ["enum.RemoveMode.Digits"] = "所有数字",
        ["enum.RemoveMode.Symbols"] = "所有符号",
        ["enum.RemoveMode.AfterMarker"] = "某段文字及其之后",
        ["enum.RemoveMode.BeforeMarker"] = "某段文字及其之前",
        ["enum.SequenceStyle.Numeric"] = "1, 2, 3",
        ["enum.SequenceStyle.Alphabetic"] = "a, b, c",
        ["enum.SequenceStyle.Roman"] = "I, II, III",
        ["enum.SequenceStyle.Base36"] = "0-9, a-z",
        ["enum.RenameScope.BaseName"] = "主文件名",
        ["enum.RenameScope.Extension"] = "扩展名",
        ["enum.RenameScope.FullName"] = "整个文件名",
        ["enum.ScanTarget.Files"] = "文件",
        ["enum.ScanTarget.Directories"] = "文件夹",
        ["enum.ScanTarget.Both"] = "文件和文件夹",
        ["enum.ConflictPolicy.Block"] = "标记出来，由我处理",
        ["enum.ConflictPolicy.AutoNumber"] = "自动加序号",
        ["enum.ConflictPolicy.Skip"] = "跳过这一项",
        ["enum.AppTheme.System"] = "跟随系统",
        ["enum.AppTheme.Light"] = "浅色",
        ["enum.AppTheme.Dark"] = "深色",
        ["enum.WindowBackdrop.None"] = "纯色",
        ["enum.WindowBackdrop.Mica"] = "云母",
        ["enum.WindowBackdrop.Acrylic"] = "亚克力"
    };

    private static Dictionary<string, string> English => new(StringComparer.Ordinal)
    {
        // ---- shell ----
        ["app.name"] = "Batch Rename Pro",
        ["app.tagline"] = "See every change before it happens",
        ["nav.rename"] = "Rename",
        ["nav.presets"] = "Presets",
        ["nav.history"] = "History",
        ["nav.settings"] = "Settings",
        ["nav.about"] = "About",
        ["nav.toggle"] = "Expand or collapse navigation",
        ["window.minimize"] = "Minimize",
        ["window.maximize"] = "Maximize",
        ["window.restore"] = "Restore down",
        ["window.close"] = "Close",

        // ---- source list ----
        ["source.title"] = "Files",
        ["source.addFolder"] = "Add folder",
        ["source.addFiles"] = "Add files",
        ["source.clear"] = "Clear",
        ["source.remove"] = "Remove from list",
        ["source.refresh"] = "Rescan",
        ["source.recursive"] = "Include subfolders",
        ["source.target"] = "Include",
        ["source.filter"] = "Filter",
        ["source.filter.hint"] = "*.jpg;*.png (empty means everything)",
        ["source.exclude.hint"] = "Exclude, e.g. *.tmp",
        ["source.empty.title"] = "No files yet",
        ["source.empty.hint"] = "Drop files or folders here, or use Add folder.",
        ["source.count"] = "{0} selected",
        ["source.dropHint"] = "Release to add",
        ["source.noneAdded"] = "Nothing in those locations matched the filter",

        // ---- rules ----
        ["rules.title"] = "Rules",
        ["rules.add"] = "Add rule",
        ["rules.empty.title"] = "No rules yet",
        ["rules.empty.hint"] = "Rules run top to bottom on every name. Add one to get started.",
        ["rules.enable"] = "Enable this rule",
        ["rules.moveUp"] = "Move up",
        ["rules.moveDown"] = "Move down",
        ["rules.duplicate"] = "Duplicate",
        ["rules.remove"] = "Remove rule",
        ["rules.clear"] = "Clear rules",
        ["rules.scope"] = "Applies to",

        ["rule.pattern.name"] = "Rename with a pattern",
        ["rule.pattern.summary"] = "Build a new name out of variables",
        ["rule.replace.name"] = "Find and replace",
        ["rule.replace.summary"] = "Swap one piece of text for another",
        ["rule.insert.name"] = "Insert text",
        ["rule.insert.summary"] = "Add text at the start, end or a position",
        ["rule.remove.name"] = "Remove characters",
        ["rule.remove.summary"] = "By position, by text or by character type",
        ["rule.case.name"] = "Change case",
        ["rule.case.summary"] = "Make capitalisation consistent",
        ["rule.extension.name"] = "Extension",
        ["rule.extension.summary"] = "Change or normalise the extension",
        ["rule.number.name"] = "Numbering",
        ["rule.number.summary"] = "Add a running counter",
        ["rule.cleanup.name"] = "Tidy up",
        ["rule.cleanup.summary"] = "Trim spaces, drop symbols, cap the length",

        // rule editors
        ["rule.pattern.label"] = "Name pattern",
        ["rule.pattern.hint"] = "for example {name}_{index:000}",
        ["rule.pattern.insertToken"] = "Insert variable",
        ["rule.replace.find"] = "Find",
        ["rule.replace.replaceWith"] = "Replace with",
        ["rule.replace.useRegex"] = "Use a regular expression",
        ["rule.replace.ignoreCase"] = "Ignore case",
        ["rule.replace.firstOnly"] = "Only the first match",
        ["rule.replace.regexHint"] = "Use $1, $2 to reference capture groups",
        ["rule.insert.text"] = "Text to insert",
        ["rule.insert.position"] = "Position",
        ["rule.insert.index"] = "Character number",
        ["rule.remove.mode"] = "Remove",
        ["rule.remove.count"] = "Characters",
        ["rule.remove.position"] = "Starting at",
        ["rule.remove.text"] = "Text",
        ["rule.remove.keep"] = "Keep these symbols",
        ["rule.case.mode"] = "Change to",
        ["rule.extension.mode"] = "Action",
        ["rule.extension.newExtension"] = "New extension",
        ["rule.number.position"] = "Position",
        ["rule.number.separator"] = "Separator",
        ["rule.number.start"] = "Start at",
        ["rule.number.step"] = "Step",
        ["rule.number.padding"] = "Digits",
        ["rule.number.style"] = "Style",
        ["rule.number.groupSize"] = "Per group",
        ["rule.sequence.title"] = "Numbering",
        ["rule.cleanup.trimEnds"] = "Trim leading and trailing spaces",
        ["rule.cleanup.collapseWhitespace"] = "Collapse repeated spaces",
        ["rule.cleanup.replaceSpaces"] = "Replace spaces with",
        ["rule.cleanup.removeDiacritics"] = "Strip accents from letters",
        ["rule.cleanup.stripInvalid"] = "Replace characters Windows rejects",
        ["rule.cleanup.invalidReplacement"] = "Replace with",
        ["rule.cleanup.maxLength.label"] = "Maximum length (0 for no limit)",

        // ---- rule diagnostics (codes emitted by the core) ----
        ["rule.pattern.empty"] = "The pattern cannot be empty.",
        ["rule.pattern.unknownToken"] = "The pattern has a variable we do not recognise; it will appear as-is in the name.",
        ["rule.replace.emptyFind"] = "Enter the text to look for.",
        ["rule.replace.badRegex"] = "The regular expression is incomplete or has a syntax error.",
        ["rule.insert.emptyText"] = "Enter the text to insert.",
        ["rule.insert.negativeIndex"] = "The position cannot be negative.",
        ["rule.remove.emptyText"] = "Enter the text to remove.",
        ["rule.remove.negativePosition"] = "The start position cannot be negative.",
        ["rule.extension.empty"] = "Enter the new extension.",
        ["rule.extension.invalidChars"] = "The extension contains characters Windows rejects.",
        ["rule.cleanup.maxLength"] = "That maximum length is short enough to erase the name.",
        ["rule.cleanup.badReplacement"] = "The replacement is itself a character Windows rejects.",
        ["rule.sequence.padding"] = "That number of digits is out of range.",
        ["rule.sequence.zeroStep"] = "A step of zero gives every file the same number.",
        ["rule.sequence.groupSize"] = "The group size must be at least 1.",
        ["rule.sequence.alphabeticStart"] = "Letter numbering has to start at 1.",
        ["rule.sequence.romanStart"] = "Roman numbering has to start at 1.",

        // ---- preview ----
        ["preview.title"] = "Preview",
        ["preview.column.original"] = "Current name",
        ["preview.column.proposed"] = "New name",
        ["preview.column.status"] = "Status",
        ["preview.empty.title"] = "The preview lands here",
        ["preview.empty.hint"] = "Pick some files, add a rule, and the new names appear as you type.",
        ["preview.showOnlyChanged"] = "Only show changes",
        ["preview.sameName"] = "(unchanged)",
        ["preview.conflictPolicy"] = "On a name clash",

        ["item.ready"] = "Will be renamed",
        ["item.unchanged"] = "Name is unchanged",
        ["item.skipped"] = "Skipped",
        ["item.missing"] = "The file is gone",
        ["item.duplicateTarget"] = "Clashes with another item in this batch",
        ["item.existsOnDisk"] = "A file on disk already has that name",
        ["item.autoResolved"] = "Numbered to avoid a clash",
        ["item.ruleError"] = "A rule is misconfigured",
        ["item.ruleFailed"] = "A rule failed on this item",

        ["name.empty"] = "The name cannot be empty.",
        ["name.invalidChars"] = "The name contains characters Windows rejects.",
        ["name.reserved"] = "That is a reserved Windows device name.",
        ["name.tooLong"] = "The name is too long.",
        ["name.trailingDotOrSpace"] = "The name cannot end with a dot or a space.",
        ["name.leadingSpace"] = "The name cannot start with a space.",

        ["summary.ready"] = "{0} to rename",
        ["summary.unchanged"] = "{0} unchanged",
        ["summary.problems"] = "{0} with problems",
        ["summary.autoResolved"] = "{0} auto-numbered",
        ["summary.nothing"] = "Nothing to rename",

        // ---- presets ----
        ["presets.title"] = "Presets",
        ["presets.subtitle"] = "Save a set of rules you use often and apply it in one click.",
        ["presets.apply"] = "Apply",
        ["presets.applied"] = "Applied the preset “{0}”",
        ["presets.save"] = "Save as preset",
        ["presets.saveCurrent"] = "Save current rules",
        ["presets.saveTitle"] = "Save preset",
        ["presets.namePrompt"] = "Give this set of rules a name",
        ["presets.nameReserved"] = "A built-in preset already uses that name. Pick another one.",
        ["presets.delete"] = "Delete preset",
        ["presets.deleteConfirm"] = "Delete the preset “{0}”?",
        ["presets.import"] = "Import…",
        ["presets.export"] = "Export…",
        ["presets.builtIn"] = "Built in",
        ["presets.custom"] = "Yours",
        ["presets.ruleCount"] = "{0} rules",
        ["presets.empty.title"] = "No presets yet",
        ["presets.empty.hint"] = "Set up your rules on the Rename page, then choose Save current rules.",
        ["presets.saved"] = "Saved the preset “{0}”",
        ["presets.imported"] = "Imported the preset “{0}”",
        ["presets.exported"] = "Exported the preset “{0}”",
        ["presets.overwrite"] = "A preset with that name exists. Overwrite it?",
        ["presets.filter"] = "Preset files (*.json)|*.json",

        ["preset.photos"] = "Photos by date",
        ["preset.photos.description"] = "Renames to 2025-11-27_001 and so on",
        ["preset.numbering"] = "Keep the name, add a number",
        ["preset.numbering.description"] = "Appends _001 to the existing name",
        ["preset.webSafe"] = "Safe for uploading",
        ["preset.webSafe.description"] = "Lowercase, hyphens for spaces, no special characters",
        ["preset.datePrefix"] = "Prefix with the modified date",
        ["preset.datePrefix.description"] = "Puts the file's own modified date in front",
        ["preset.tidy"] = "Tidy messy names",
        ["preset.tidy.description"] = "Collapses spaces, drops stray symbols, trims the ends",
        ["preset.lowerExt"] = "Lowercase the extension",
        ["preset.lowerExt.description"] = "Turns .JPG into .jpg and nothing else",

        // ---- tokens ----
        ["tokens.title"] = "Variables",
        ["tokens.hint"] = "Click one to drop it into the pattern.",
        ["tokens.category.text"] = "Text",
        ["tokens.category.number"] = "Numbers",
        ["tokens.category.time"] = "Dates",
        ["tokens.category.unique"] = "Unique",

        ["token.name"] = "The base name as it stands now",
        ["token.ext"] = "The extension, dot included",
        ["token.original"] = "The untouched original file name",
        ["token.parent"] = "The containing folder's name",
        ["token.nameUpper"] = "The base name in upper case",
        ["token.nameLower"] = "The base name in lower case",
        ["token.nameTitle"] = "The base name in title case",
        ["token.index"] = "Position in the batch",
        ["token.indexPadded"] = "Position padded to three digits",
        ["token.total"] = "How many files are in the batch",
        ["token.size"] = "File size in bytes",
        ["token.sizeMb"] = "File size in megabytes",
        ["token.date"] = "Today's date",
        ["token.time"] = "The current time",
        ["token.dateFormat"] = "A date in a format you choose",
        ["token.created"] = "When the file was created",
        ["token.modified"] = "When the file was last changed",
        ["token.year"] = "Year",
        ["token.month"] = "Month",
        ["token.day"] = "Day",
        ["token.guid"] = "A random unique identifier",
        ["token.rand"] = "Six random characters",

        // ---- actions ----
        ["action.run"] = "Rename",
        ["action.runCount"] = "Rename {0} items",
        ["action.cancel"] = "Cancel",
        ["action.close"] = "Close",
        ["action.ok"] = "OK",
        ["action.undo"] = "Undo",
        ["action.undoLast"] = "Undo last run",
        ["action.retry"] = "Try again",
        ["action.copy"] = "Copy",
        ["action.openFolder"] = "Open containing folder",
        ["action.toggleTheme"] = "Switch between light and dark",
        ["action.dismiss"] = "Got it",

        ["run.confirmTitle"] = "Confirm rename",
        ["run.confirmBody"] = "About to rename {0} items. You can undo this afterwards.",
        ["run.working"] = "Renaming…",
        ["run.progress"] = "{0} of {1}",
        ["run.done"] = "Renamed {0} items",
        ["run.undone"] = "Undid {0} renames",
        ["run.cancelled"] = "Cancelled — everything is back the way it was",
        ["run.failed"] = "The rename failed",
        ["run.rolledBack"] = "Something went wrong. Every change was undone and your files are untouched.",
        ["run.unrecovered"] = "Something went wrong and {0} items could not be put back. See the history page.",

        // ---- history ----
        ["history.title"] = "History",
        ["history.subtitle"] = "Every batch you have run, and the undo button for each one.",
        ["history.empty.title"] = "Nothing here yet",
        ["history.empty.hint"] = "Once you rename a batch it shows up here, ready to undo.",
        ["history.itemCount"] = "{0} items",
        ["history.multipleFolders"] = "Several folders",
        ["history.undo"] = "Undo this run",
        ["history.undoConfirm"] = "This puts the names of all {0} items back the way they were. Continue?",
        ["history.forget"] = "Remove from history, leaving files alone",
        ["history.clear"] = "Clear history",
        ["history.clearConfirm"] = "Forget every record? Your files are not touched.",
        ["history.undone"] = "Undone",
        ["history.undoFailed"] = "Could not undo — the files may have been moved or renamed since.",

        // ---- settings ----
        ["settings.title"] = "Settings",
        ["settings.subtitle"] = "Changes take effect straight away — there is nothing to save.",
        ["settings.section.appearance"] = "Appearance",
        ["settings.theme"] = "Theme",
        ["settings.theme.hint"] = "Match Windows follows the light and dark setting of the system.",
        ["settings.backdrop"] = "Window material",
        ["settings.backdrop.hint"] = "Needs Windows 11 22H2 or newer; falls back to solid where it is unavailable.",
        ["settings.backdrop.unavailable"] = "This build of Windows cannot draw window materials. The choice is saved and applies once you upgrade.",
        ["settings.language"] = "Language",
        ["settings.language.hint"] = "Applies immediately, no restart needed.",
        ["settings.navigationExpanded"] = "Start with the sidebar expanded",
        ["settings.section.defaults"] = "Defaults",
        ["settings.confirmBeforeRun"] = "Ask before renaming",
        ["settings.confirmBeforeRun.hint"] = "With this off, Rename runs immediately — you can still undo it.",
        ["settings.recursive"] = "Include subfolders by default",
        ["settings.recursive.hint"] = "Whether adding a folder also scans everything nested inside it.",
        ["settings.scanTarget"] = "Scan for",
        ["settings.conflictPolicy"] = "On a name clash",
        ["settings.conflictPolicy.hint"] = "What to do by default when two files want the same name.",
        ["settings.historyLimit"] = "History entries to keep",
        ["settings.historyLimit.hint"] = "Between 5 and 500. Older entries beyond the limit are pruned.",
        ["settings.section.data"] = "Data",
        ["settings.dataFolder"] = "Data folder",
        ["settings.openDataFolder"] = "Open data folder",
        ["settings.reset"] = "Reset to defaults",
        ["settings.reset.hint"] = "Only settings are reset. Presets and history are left alone.",
        ["settings.resetConfirm"] = "Put every setting back to its default?",
        ["settings.resetDone"] = "Settings reset",

        // ---- about ----
        ["about.version"] = "Version",
        ["about.repository"] = "Project home",
        ["about.issues"] = "Report an issue",
        ["about.license"] = "Licence",
        ["about.license.mit"] = "MIT Licence",
        ["about.environment"] = "Environment",
        ["about.runtime"] = ".NET runtime",
        ["about.os"] = "Operating system",
        ["about.tokens"] = "Variable reference",
        ["about.tokens.hint"] = "These go inside the pattern of the “Rename with a pattern” rule.",
        ["about.copyright"] = "Open source under the MIT Licence — use it, change it, ship it.",

        // ---- generic ----
        ["common.yes"] = "Yes",
        ["common.no"] = "No",
        ["common.on"] = "On",
        ["common.off"] = "Off",
        ["common.search"] = "Search",
        ["common.none"] = "None",
        ["common.error"] = "Something went wrong",
        ["common.warning"] = "Heads up",
        ["common.loading"] = "Loading…",
        ["error.unexpected"] = "Something unexpected went wrong: {0}",
        ["error.unexpected.fallback"] = "The application hit an unexpected error and has to close. The details are in the log file.",
        ["time.justNow"] = "just now",
        ["time.minutesAgo"] = "{0} minutes ago",
        ["time.hoursAgo"] = "{0} hours ago",
        ["time.daysAgo"] = "{0} days ago",

        // ---- enums ----
        ["enum.CaseMode.Lower"] = "lower case",
        ["enum.CaseMode.Upper"] = "UPPER CASE",
        ["enum.CaseMode.Title"] = "Title Case",
        ["enum.CaseMode.Sentence"] = "Sentence case",
        ["enum.CaseMode.Invert"] = "iNVERT cASE",
        ["enum.ExtensionMode.Keep"] = "Leave alone",
        ["enum.ExtensionMode.Lower"] = "Lowercase it",
        ["enum.ExtensionMode.Upper"] = "Uppercase it",
        ["enum.ExtensionMode.Replace"] = "Replace with",
        ["enum.ExtensionMode.Remove"] = "Remove it",
        ["enum.ExtensionMode.AddIfMissing"] = "Add only if missing",
        ["enum.InsertPosition.Prefix"] = "At the start",
        ["enum.InsertPosition.Suffix"] = "At the end",
        ["enum.InsertPosition.AtIndex"] = "Before character N from the left",
        ["enum.InsertPosition.FromEnd"] = "Before character N from the right",
        ["enum.RemoveMode.FromStart"] = "The first N characters",
        ["enum.RemoveMode.FromEnd"] = "The last N characters",
        ["enum.RemoveMode.Range"] = "N characters at a position",
        ["enum.RemoveMode.Text"] = "Some text",
        ["enum.RemoveMode.Digits"] = "Every digit",
        ["enum.RemoveMode.Symbols"] = "Every symbol",
        ["enum.RemoveMode.AfterMarker"] = "Some text and everything after it",
        ["enum.RemoveMode.BeforeMarker"] = "Some text and everything before it",
        ["enum.SequenceStyle.Numeric"] = "1, 2, 3",
        ["enum.SequenceStyle.Alphabetic"] = "a, b, c",
        ["enum.SequenceStyle.Roman"] = "I, II, III",
        ["enum.SequenceStyle.Base36"] = "0-9, a-z",
        ["enum.RenameScope.BaseName"] = "Base name",
        ["enum.RenameScope.Extension"] = "Extension",
        ["enum.RenameScope.FullName"] = "Whole name",
        ["enum.ScanTarget.Files"] = "Files",
        ["enum.ScanTarget.Directories"] = "Folders",
        ["enum.ScanTarget.Both"] = "Files and folders",
        ["enum.ConflictPolicy.Block"] = "Flag it and let me decide",
        ["enum.ConflictPolicy.AutoNumber"] = "Add a number",
        ["enum.ConflictPolicy.Skip"] = "Skip that item",
        ["enum.AppTheme.System"] = "Match Windows",
        ["enum.AppTheme.Light"] = "Light",
        ["enum.AppTheme.Dark"] = "Dark",
        ["enum.WindowBackdrop.None"] = "Solid",
        ["enum.WindowBackdrop.Mica"] = "Mica",
        ["enum.WindowBackdrop.Acrylic"] = "Acrylic"
    };
}
